changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - major
    - title: New Features & Components 🎉
      labels:
        - minor
    - title: Fixes
      labels:
        - patch
    - title: Other Changes
      labels:
        - "*"
