export const category = {
  USE: 'USE',
  CAUTION: 'USE WITH CAUTION',
  DONT_USE: "DON'T USE",
};

export const level = {
  AVAILABLE: 'AVAILABLE',
  BEST_PRACTICE: 'BEST PRACTICE',
  CANDIDATE: 'CANDIDATE',
  DEPLOYED: 'DEPLOYED',
  DEPRECATED: 'DEPRECATED',
  PROPOSED: 'PROPOSED',
};
