import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * VA Team Documentation Sidebars
 */
const sidebars: SidebarsConfig = {
  // Meetings
  meetingsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'meetings',
    },
  ],

  // Architecture Decisions (ADRs)
  architectureSidebar: [
    {
      type: 'autogenerated',
      dirName: 'architecture',
    },
  ],

  // Processes
  processesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'processes',
    },
  ],

  // Onboarding
  onboardingSidebar: [
    {
      type: 'autogenerated',
      dirName: 'onboarding',
    },
  ],
};

export default sidebars;
