#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Get the current branch name
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# Calculate the length of the branch name
BRANCH_NAME_LENGTH=${#BRANCH_NAME}

# Check if the length is greater than 37
if [ $BRANCH_NAME_LENGTH -gt 37 ]; then
  echo "Length of the current branch name is: $BRANCH_NAME_LENGTH"
  echo "Branch name length is greater than 37 characters."
  exit 1
fi

VALID_BRANCH_REGEX='^[a-z\d]+[a-z\d\-]*'

if [[ ! $BRANCH_NAME =~ $VALID_BRANCH_REGEX ]]; then
  echo "Invalid branch name, name must start with a lowercase letter or"
  echo "number, and include only lowercase letters, numbers, and dashes."
  exit 1
fi
