#
# Lint and Unit Test jobs that runs our lint:ci and test npm scripts
#

name: '[Code Quality] Mobile CI Testing'

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install