#
# Lint and Unit Test jobs that runs our lint:ci and test npm scripts
#

name: 'Mobile Documentation'

on:
  pull_request:

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'
      - run: yarn install
