name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    paths-ignore:
      - 'mobile-components/**'
      - 'mobile-documentation/**'
      - 'mobile-icons/**'
      - 'mobile-linting/**'
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: "patch, minor, major, ignore-for-release"
