name: Weekly Design System Reports

on:
  schedule:
    - cron: '0 22 * * 4' # Run every Thursday at 10 PM UTC (6 PM EDT / 5 PM EST)
  workflow_dispatch: # Allow manual triggering

jobs:
  generate-weekly-reports:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout component-library
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref || github.ref_name }}
        fetch-depth: 1
        
    - name: Checkout vets-website
      uses: actions/checkout@v4
      with:
        repository: department-of-veterans-affairs/vets-website
        path: vets-website
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1
        
    - name: Checkout content-build
      uses: actions/checkout@v4
      with:
        repository: department-of-veterans-affairs/content-build
        path: content-build
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install
      
    - name: Create correct .env.json for GitHub Actions
      working-directory: packages/design-system-dashboard-cli
      run: |
        echo '{
          "repos": {
            "vets-website": "../../vets-website/",
            "content-build": "../../content-build/"
          }
        }' > .env.json.github
        
    - name: Create output directory
      working-directory: packages/design-system-dashboard-cli
      run: mkdir -p output
        
    - name: Generate forms report
      working-directory: packages/design-system-dashboard-cli
      run: |
        # Temporarily replace .env.json with GitHub paths
        mv .env.json .env.json.original
        mv .env.json.github .env.json
        
        yarn forms --csv --output output/form-apps-$(date +%Y-%m-%d).csv
        
        # Restore original .env.json
        mv .env.json.original .env.json
        
    - name: Generate design system components report
      working-directory: packages/design-system-dashboard-cli
      run: |
        # Create GitHub-specific .env.json
        echo '{
          "repos": {
            "vets-website": "../../vets-website/",
            "content-build": "../../content-build/"
          }
        }' > .env.json.github
        
        # Temporarily replace .env.json with GitHub paths
        mv .env.json .env.json.original
        mv .env.json.github .env.json
        
        yarn report:csv --output output/ds-components-$(date +%Y-%m-%d).csv
        
        # Restore original .env.json
        mv .env.json.original .env.json
        
    - name: Generate forms library usage report
      working-directory: packages/design-system-dashboard-cli
      run: |
        # Create GitHub-specific .env.json
        echo '{
          "repos": {
            "vets-website": "../../vets-website/",
            "content-build": "../../content-build/"
          }
        }' > .env.json.github
        
        # Temporarily replace .env.json with GitHub paths
        mv .env.json .env.json.original
        mv .env.json.github .env.json
        
        yarn forms-library-usage --list > output/forms-library-usage-$(date +%Y-%m-%d).txt
        
        # Restore original .env.json
        mv .env.json.original .env.json
      
    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: reports-${{ github.run_number }}
        path: |
          packages/design-system-dashboard-cli/output/*.csv
          packages/design-system-dashboard-cli/output/*.txt
        retention-days: 7

           
    - name: Commit and push reports
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add packages/design-system-dashboard-cli/output/form-apps-$(date +%Y-%m-%d).csv
        git add packages/design-system-dashboard-cli/output/ds-components-$(date +%Y-%m-%d).csv
        git add packages/design-system-dashboard-cli/output/forms-library-usage-$(date +%Y-%m-%d).txt
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add weekly reports for $(date +%Y-%m-%d)"
          git push
        fi
