name: Weekly Design System Reports

on:
  schedule:
    - cron: '0 22 * * 4' # Run every Thursday at 10 PM UTC (6 PM EDT / 5 PM EST)
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - '.github/workflows/weekly-reports.yml'
      - 'packages/design-system-dashboard-cli/**'
  workflow_dispatch: # Allow manual triggering

jobs:
  generate-weekly-reports:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout component-library
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref || github.ref_name }}
        fetch-depth: 1
        
    - name: Checkout vets-website
      uses: actions/checkout@v4
      with:
        repository: department-of-veterans-affairs/vets-website
        path: vets-website
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1
        
    - name: Checkout content-build
      uses: actions/checkout@v4
      with:
        repository: department-of-veterans-affairs/content-build
        path: content-build
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install
      
    - name: Create correct .env.json for GitHub Actions
      working-directory: packages/design-system-dashboard-cli
      run: |
        echo '{
          "repos": {
            "vets-website": "../../vets-website/",
            "content-build": "../../content-build/"
          }
        }' > .env.json.github
        
    - name: Create output directory
      working-directory: packages/design-system-dashboard-cli
      run: mkdir -p output
        
    - name: Generate forms report
      working-directory: packages/design-system-dashboard-cli
      run: |
        # Temporarily replace .env.json with GitHub paths
        mv .env.json .env.json.original
        mv .env.json.github .env.json
        
        yarn forms --csv --output output/form-apps-$(date +%Y-%m-%d).csv
        
        # Restore original .env.json
        mv .env.json.original .env.json
        
    - name: Generate design system components report
      working-directory: packages/design-system-dashboard-cli
      run: |
        # Create GitHub-specific .env.json
        echo '{
          "repos": {
            "vets-website": "../../vets-website/",
            "content-build": "../../content-build/"
          }
        }' > .env.json.github
        
        # Temporarily replace .env.json with GitHub paths
        mv .env.json .env.json.original
        mv .env.json.github .env.json
        
        yarn report:csv --output output/ds-components-$(date +%Y-%m-%d).csv
        
        # Restore original .env.json
        mv .env.json.original .env.json
        
    - name: Generate forms library usage report
      working-directory: packages/design-system-dashboard-cli
      run: |
        # Create GitHub-specific .env.json
        echo '{
          "repos": {
            "vets-website": "../../vets-website/",
            "content-build": "../../content-build/"
          }
        }' > .env.json.github
        
        # Temporarily replace .env.json with GitHub paths
        mv .env.json .env.json.original
        mv .env.json.github .env.json
        
        yarn forms-library-usage --list > output/forms-library-usage-$(date +%Y-%m-%d).txt
        
        # Restore original .env.json
        mv .env.json.original .env.json
      
    - name: Get current date
      id: date
      run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
      
    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: reports-${{ github.run_number }}
        path: |
          packages/design-system-dashboard-cli/output/*.csv
          packages/design-system-dashboard-cli/output/*.txt
        retention-days: 7

           
    - name: Commit reports to weekly branch
      run: |
        # Create a new branch for this week's reports
        git checkout -b weekly-reports/${{ steps.date.outputs.date }}
        
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add and commit the reports
        git add packages/design-system-dashboard-cli/output/form-apps-${{ steps.date.outputs.date }}.csv
        git add packages/design-system-dashboard-cli/output/ds-components-${{ steps.date.outputs.date }}.csv
        git add packages/design-system-dashboard-cli/output/forms-library-usage-${{ steps.date.outputs.date }}.txt
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        else
          git commit -m "Add weekly reports for ${{ steps.date.outputs.date }}"
          git push origin weekly-reports/${{ steps.date.outputs.date }}
          
          echo "## 📊 Weekly Reports Generated!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Branch created: \`weekly-reports/${{ steps.date.outputs.date }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Manual step required:** Create a PR from this branch to main." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Reports generated:" >> $GITHUB_STEP_SUMMARY
          echo "- form-apps-${{ steps.date.outputs.date }}.csv" >> $GITHUB_STEP_SUMMARY
          echo "- ds-components-${{ steps.date.outputs.date }}.csv" >> $GITHUB_STEP_SUMMARY
          echo "- forms-library-usage-${{ steps.date.outputs.date }}.txt" >> $GITHUB_STEP_SUMMARY
        fi
