name: Test Form Apps Report

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch: # Allow manual triggering

jobs:
  test-form-report:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout component-library
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref || github.ref_name }}
        fetch-depth: 1
        
    - name: Checkout vets-website
      uses: actions/checkout@v4
      with:
        repository: department-of-veterans-affairs/vets-website
        path: vets-website
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install
      
    - name: Create correct .env.json for GitHub Actions
      working-directory: packages/design-system-dashboard-cli
      run: |
        echo '{
          "repos": {
            "vets-website": "../../vets-website/",
            "content-build": "../../content-build/"
          }
        }' > .env.json.github
        
    - name: Debug environment
      working-directory: packages/design-system-dashboard-cli
      run: |
        echo "=== Current directory ==="
        pwd
        echo "=== Repository structure ==="
        ls -la ../../
        echo "=== vets-website structure ==="
        ls -la ../../vets-website/src/applications/ | head -10
        echo "=== .env.json content ==="
        cat .env.json.github
        
    - name: Create output directory
      working-directory: packages/design-system-dashboard-cli
      run: mkdir -p output
        
    - name: Test forms report with GitHub paths
      working-directory: packages/design-system-dashboard-cli
      run: |
        # Temporarily replace .env.json with GitHub paths
        mv .env.json .env.json.original
        mv .env.json.github .env.json
        
        echo "=== Testing yarn forms command ==="
        yarn forms --list
        echo "=== Generating CSV ==="
        yarn forms --csv --output output/form-apps-test.csv
        
        echo "=== Checking output ==="
        ls -la output/
        wc -l output/form-apps-test.csv
        head -10 output/form-apps-test.csv
        
        # Restore original .env.json
        mv .env.json.original .env.json
      
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-form-report-${{ github.run_number }}
        path: packages/design-system-dashboard-cli/output/form-apps-test.csv
        retention-days: 7
